### ISSUE TITLE
Option to display errors on save

### ISSUE THREAD

**Issue by dandavison** [purcell/reformatter.el#12]
This package looks great, thanks!

I would like an option to display errors when the function is called in the `before-save-hook`, in the same way as it does for `myformatter-buffer`.

See also #3.

**Comment by purcell** [comment]
Thanks! Since this is a variation of #3, I'll close this to avoid duplication, but happy to discuss further there. I'm probably going to implement something like this, fwiw: just haven't decided what shape to make it, and I'm being super conservative with this package since such options will affect how consistent `reformatter`-based packages will be.
