### ISSUE TITLE
reformatter-define macro always yields two warnings when being byte-compiled

### ISSUE THREAD

**Issue by terlar** [purcell/reformatter.el#29]
For every formatter defined with `reformatter-define` I get the following warnings when trying to byte-compile:

```
 1468  22 warning  ‘make-variable-buffer-local’ not called at toplevel
 1468  22 warning  defcustom for ‘NAME-on-save-mode-lighter’ fails to specify containing group
```

Would it be possible to avoid this?

**Edit**
I also seem to get:
```
the following functions are not known to be defined: NAME-region
```

**Comment by purcell** [comment]
Can you provide a full example please? For instance, for the second warning it looks like you are not supplying `:group`, so that would be to be expected.

**Comment by purcell** [comment]
FWIW, I haven't seen these warnings locally or in CI for packages which use `reformatter`.

**Comment by terlar** [comment]
Interesting, I guess I should just actually read the docs, missed the part about `:group`. I only had this configuration:
```
(use-package reformatter
  :ensure t
  :demand t
  :config
  (reformatter-define black :program "black" :args '("-"))
  (reformatter-define nixfmt :program "nixfmt"))
```

I will have another look to see if there is something else at play. But it was those lines it complained about and there is not much else going on there. Could it be due to a newer version of Emacs?

**Comment by terlar** [comment]
Seems the two top ones disappeared when specifying the group. Still see the the:
```
the following functions are not known to be defined: NAME-region
```

But perhaps that is something related to the use of `use-package` or some other part. Although no code is referring to this.

I will close this and assume the error is on my end. Thank you for the support.

**Comment by TLATER** [comment]
I've finally gotten around to trying to purge all these flymake errors from my emacs config, and am seeing the same thing. I can work around most of the warnings by explicitly telling `use-package` about functions that `reformatter` generates, however:

```elisp
(use-package reformatter
  :commands (alejandra-format-region alejandra-format-buffer)
  :functions reformatter--do-region
  :config
  (reformatter-define alejandra-format
    :program "alejandra"
    :group 'nix-mode
    :lighter " AL"))
```

Yields:

```
warning  e-f-b-c  ‘make-variable-buffer-local’ not called at toplevel
```

Curiously, that function doesn't appear at all in the source of `reformatter`. The warning points at the `:group` portion of the macro, but that's probably a red herring, because it showed that before I specified a `group` too. Any idea where this might come from?

I can imagine it being caused by the indirection of using `defcustom` in a macro, and just an inherent issue with `reformatter`, but in that case it'd be good to at least document why that's a problem and if there is anything that can be done about this warning.

**Comment by TLATER** [comment]
Having dug a little further, see this post on the emacs mailing list: https://lists.gnu.org/archive/html/bug-gnu-emacs/2013-08/msg00549.html

AIUI a false positive, this usage is fine, but it's warned about because it indicates that a user might be confused. Well, I *believe* I'm not confused, at best this is an upstream issue caused by my usage, so let's just disable that warning for now:

```elisp
(use-package reformatter
  :commands (alejandra-format-region alejandra-format-buffer)
  :functions reformatter--do-region
  :config
  ;; Work around `make-variable-buffer-local' being called at a
  ;; non-top-level.
  ;;
  ;; Note: Do not do this without first checking if no other warnings
  ;; are thrown. In theory, we could use `with-suppressed-warnings',
  ;; but it doesn't look like there's any documentation on how to
  ;; disable this particular warning, and grepping the emacs source
  ;; for `make-variable-buffer-local' didn't yield anything useful.
  (with-no-warnings ((make-variable-buffer-local))
    (reformatter-define alejandra-format
      :program "alejandra"
      :group 'nix-mode
      :lighter " AL")))
```
