### ISSUE TITLE
evil support

### ISSUE THREAD

**Issue by wbolster** [purcell/reformatter.el#7]
first of all, thanks for this package! i started writing something similar a while ago, parked it, and then `reformatter.el` appeared which is better than i could wish for. :)

that said, i'm interested in using this package with `evil`.

defining an `evil` operator (a special command that operates on a region of text) that calls a normal elisp command that operates on a range of text, looks like this:

``` elisp
(evil-define-operator foo-evil (beg end type)
  (interactive "<R>")
  (foo-region beg end))
```

what are your thoughts on having `reformatter.el` automatically define a command like the above when `evil` is available?

**Comment by purcell** [comment]
Thanks for writing this!

It's not good for packages to have add-on magical behaviour that varies according to what other packages are installed, and it's even hairier when we're talking about a macro that generates such code. Imagine a `fooformat` package which uses `reformatter` -- should `fooformat` call `reformatter-define` *with* or *without* the `evil-operator` option? If with, then `fooformat` would have to declare an `evil` dependency, but why should the `fooformat` author need to decide whether his users should have `evil` installed?

So, as you've shown, since it's pretty easy to define an operator anyway, if you'd like to submit a doc PR which adds an example of how to define an evil operator for the generated command to the README / Commentary, that'd be my preferred approach. :-)

**Comment by wbolster** [comment]
hmmm. i think defining a `...-evil` command from the macro should not be dependent on a flag passed to `reformatter-define`, as you seem to imply.

if evil is available, `reformatter` would just unconditionally define an evil operator.

(see also #9 with generic helpers. a single `reformatter-dwim-evil` helper is actually all i need to have a keybinding for reformatting regardless of the current buffer's major mode.)

**Comment by purcell** [comment]
> f evil is available, `reformatter` would just unconditionally define an evil operator.

What would "available" mean, here? Since `reformatter` uses a macro, "available" must be something determined at compile-time, so what if you install a reformatter-based library "xformat" first, then install "evil" later? The byte code for "xformat" would then contain no code relating to "evil": "xformat.el" would have to be recompiled for the evil support to appear, which is problematic.

**Comment by wbolster** [comment]
unfortunately, conditional dependencies in elisp are a bit of a pain in practice indeed :(
